#!/bin/bash

#
# Copyright (C) 2014 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#
#
#
# This script will install NethServer.
# Default installation will include only base system.
# If you need to install more modules, you can specifies them on the command line.
#
# Default installtion:
# 
#     nethserver-install
#
# Install mail server
#
#     nethserver-install mail-server
#
#

function log {
    echo `date` "$1" >> /var/log/nethserver-install.log
}

function logexec {
    cmd=$1
    log "$cmd"
    { $cmd 2>&1 || exit 1 ; } | tee -a /var/log/nethserver-install.log
}

function end {
    echo
    echo "You can access the Web interface at:"
    hostname=`/sbin/e-smith/db configuration get SystemName`
    domainname=`/sbin/e-smith/db configuration get DomainName`
    echo
    echo -n "    https://$hostname.$domainname:980"
    for k in `/sbin/e-smith/db networks keys`
    do
       role=`/sbin/e-smith/db networks getprop $k role`
       if [ "$role" == "green" ]; then
           ip=$(/sbin/e-smith/db networks getprop $k ipaddr)
           echo " (or https://$ip:980)"
       fi
    done
    echo 
    echo "    Login: root" 
    echo "    Password: <your_root_password>"
    echo
    echo
    echo "Installation logs can be found:"

    echo "/var/log/nethserver-install.log"
    echo "/var/log/nethserver-install-journalctl.log"
	echo
	echo
    log "End"
    exit 0
}

rpm -q nethserver-base >/dev/null
if [ $? -eq 0 ]; then
   echo
   echo "NethServer is already installed!"
   log "Already installed"
   end
fi

/sbin/nethserver-arm-preconf
if [[ $? -ne 0 ]]; then
   exit 0
fi


log "Starting installation"
echo "Starting installation process. It will take a while..."
echo
logexec "yum -y --disablerepo=* --enablerepo=extras,base,updates install deltarpm"
#simlink for missing epel.repo
if [ ! -f /etc/yum.repos.d/epel.repo ]; then
   ln -s /etc/yum.repos.d/NethServer.ns-epel /etc/yum.repos.d/epel.repo
fi
##logexec "rpm --import /etc/pki/rpm-gpg/*"
logexec "yum -y --disablerepo=* --enablerepo=nethserver-base,nethserver-updates,base,updates,epel,extras install @nethserver-arm"

rpm -q nethserver-base >/dev/null
if [[ $? -ne 0 ]]; then
   log "Can not install base system; stopping nethserver-install"
   echo
   echo "Something went wrong installing base system"
   exit $?
else
  logexec "systemctl stop firewalld"
  logexec "systemctl disable firewalld"
fi

touch /var/spool/first-boot
echo
echo "Configuring system, please wait...     (this can take over 5 minutes)"
echo
###logexec "systemctl start nethserver-system-init.service"

if [[ $? -eq 0 ]]; then 
     log "yum group mark-remove core"
     yum group mark-remove core > /dev/null 2>&1
fi

echo
for UNIT in NetworkManager firewalld; do
    if systemctl is-active -q $UNIT; then
        logexec "systemctl stop $UNIT"
        logexec "systemctl preset $UNIT"
    fi
done
logexec "/sbin/e-smith/signal-event system-init"

# devel-debug : write journalctl to log
journalctl -x > /var/log/nethserver-install-journalctl.log
end
