#!/bin/bash
#
# WIP: final goal would be a interactive "NOOB" configuration:
#    - resize rootfs ?
#    - set hostname ?
#    - install ntp/cronie for nice install log ?
#    - overclock for a bit more oomph ?
#

#check hostname=FQDN
function chk_fqdn {
    chk_fqdn=0
    cat /etc/hostname | grep '\.' > /dev/null
    if [[ $? -ne 0 ]]; then
       chk_fqdn=1
       echo -e "\033[1mWARNING:\033[0m  Hostname does not represent fully qualified domain name(FQDN)"
       hostname -A | grep '\.' > /dev/null
       if [[ $? -eq 0 ]]; then
          host_ctl=$(hostname -A)
          echo "          FQDN Fetched from network: $host_ctl"
       else
          host_ctl=$(cat /etc/hostname).localdomain
       fi
       echo -e "          Hostname $host_ctl will be set\n"
    fi
}

#apply settings FQDN hostname, locale
function app_set {
    if [[ chk_fqdn -ne 0 ]]; then
       hostnamectl set-hostname $host_ctl
    fi
    localectl set-locale LANG=en_US.utf8
    # CentOS Userland enables irqbalance by default;
    # it has a memory leak and is useless on most arm boards
    systemctl stop irqbalance > /dev/null 2>&1
    systemctl disable irqbalance > /dev/null 2>&1
}

unaloc=$(parted /dev/mmcblk0 unit GB print free | grep 'Free Space' | tail -n1 | awk '{print $3}')
sdsize=$(parted /dev/mmcblk0 unit GB print | grep '/dev/mmcblk0' | awk '{print $3}')
max_cpu=$(sed 's/.\{3\}$//' /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq)
root_fs=$(df -h | grep '/dev/root')
avail_fs="$(echo $root_fs | awk '{print $4}')B"
root_fs="$(echo $root_fs | awk '{print $2}')B"

clear
echo -e "\n\n    `date '+%a %d %B %Y %H:%M'`\n\n"
echo -e "   \033[1mWelcome to Nethserver-Arm\033[0m\n\n"
echo -e "This is your current system setup: \n"

echo -e "      Size SD-Card: $sdsize"
echo -e "Free space SD-Card: $unaloc"
echo -e "       Size RootFS: $root_fs"
echo -e "  Available RootFS: $avail_fs"

echo -e " Max CPU Frequenty: $max_cpu MHz\n"

echo -e "$(hostnamectl status)\n"
echo -e "  $(timedatectl | grep 'Time zone')"
echo -e "  $(localectl status | grep 'System Locale')\n"

chk_fqdn

read -p "Do you want to continue installing Nethsever-Arm (y/N) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    exit 1
fi

app_set
exit 0
